name: Contribute
main: io.github.jisaacs1207.contribute.Contribute
version: 0.1
author: jisaacs1207
website: http://fivekingdoms.net
depend: [Vault]
description: >
             Contribute materials to your faction!

commands:
   contribute:
      description: Contribute materials to your faction!
      aliases: [ctb]